"""Story 007, sub-task 4.1 -- the audit of the 2026-10-05 equivalence diff, as data.

Two kde rootfs built apart differed only in files generated by the build. Each of
them is either a secret (deny-listed, with the package that generates it) or
recorded in livecd.yaml as not secret, with its class: ``secret`` (a key, a seed,
a credential), ``identity`` (machine-specific but public) or ``derived``
(deterministic from content). A generated PUBLIC file wrongly deny-listed would
fail every assemble -- so the shipped list is checked against those files too.
"""

import re
from pathlib import Path

from shidashi import config, system
from tests.test_system import _configure, _kde

#: What the equivalence diff found (memory: shidashi-iso-speedup-plan, 2026-10-05),
#: each as the alternative spellings a comment may use for it.
_DIFF = {
    "initramfs": ("initramfs",),
    "UKI": ("uki", "efi/linux"),
    "os-release": ("os-release",),
    "rndc.key": ("rndc.key",),
    "shadow salt": ("shadow",),
    "NSS .chk": (".chk",),
    "hwdb": ("hwdb",),
    "installkernel": ("installkernel",),
    "passwd/group order": ("passwd",),
}
_CLASS = re.compile(r"\b(secret|identity|derived)\b", re.IGNORECASE)
#: A Gentoo package atom: category/name (net-dns/bind, sys-apps/systemd).
_ATOM = re.compile(r"\b(?:[a-z0-9]+-[a-z0-9]+|virtual)/[A-Za-z0-9][A-Za-z0-9+_.-]*")


def _livecd_lines() -> list[str]:
    return (config.variants_dir() / system.LIVECD_FILE).read_text().splitlines()


def _comments() -> list[str]:
    return [ln.split("#", 1)[1] for ln in _livecd_lines() if "#" in ln]


def test_every_path_of_the_equivalence_diff_is_classified() -> None:
    comments = _comments()
    for item, spellings in _DIFF.items():
        classified = [
            c for c in comments if any(s in c.lower() for s in spellings) and _CLASS.search(c)
        ]
        assert classified, f"{item}: no livecd.yaml comment names it with its class"


def _deny_entries() -> list[tuple[str, str]]:
    """Each ``build_time_secrets`` entry with the comment that covers it: its own
    inline comment, else the nearest comment above it inside the list."""
    lines = _livecd_lines()
    start = next(
        (i for i, ln in enumerate(lines) if re.match(r"^build_time_secrets:\s*$", ln)), None
    )
    assert start is not None, "livecd.yaml has no build_time_secrets list"
    entries: list[tuple[str, str]] = []
    above = ""
    for line in lines[start + 1 :]:
        if re.match(r"^[A-Za-z_]", line):
            break  # the next top-level key
        stripped = line.strip()
        if stripped.startswith("#"):
            above = stripped
        elif stripped.startswith("- "):
            value, _, inline = stripped[2:].partition("#")
            entries.append((value.strip().strip("'\""), inline or above))
    return entries


def test_every_deny_list_entry_names_the_package_that_generates_it() -> None:
    entries = _deny_entries()
    shipped = system.load_livecd(config.variants_dir()).build_time_secrets
    assert {p for p, _ in entries} == set(shipped)
    for pattern, comment in entries:
        assert _ATOM.search(comment), f"{pattern}: no generating package in {comment!r}"


def _plant(rootfs: Path, *paths: str) -> None:
    for rel in paths:
        (rootfs / rel).parent.mkdir(parents=True, exist_ok=True)
        (rootfs / rel).write_text(f"generated at build time: {rel}\n")


def test_the_shipped_list_names_its_secrets_and_none_of_the_generated_public_files(
    tmp_path: Path,
) -> None:
    """Hostile half first: the files the diff found that are NOT secret, in a
    configured image beside its os-release, shadow, passwd and group, are never
    named. Then each initial secret is."""
    cfg = _kde()
    image, _ = _configure(tmp_path, cfg)
    public = (
        "boot/initramfs-6.12.0.img",
        "boot/EFI/Linux/bentoo-6.12.0.efi",
        "etc/udev/hwdb.bin",
        "usr/lib/udev/hwdb.bin",
        "usr/lib64/libsoftokn3.chk",
        "usr/lib64/libfreebl3.chk",
        "etc/ssh/ssh_host_ed25519_key.pub",
        "etc/bind/named.conf",
    )
    _plant(image.rootfs, *public)
    assert system.verify(image.rootfs, cfg, init="systemd", live=True) == []
    secrets = (
        "etc/bind/rndc.key",
        "etc/ssh/ssh_host_ed25519_key",
        "var/lib/systemd/random-seed",
        "var/lib/systemd/credential.secret",
    )
    _plant(image.rootfs, *secrets)
    problems = system.verify(image.rootfs, cfg, init="systemd", live=True)
    for path in secrets:
        assert sum(path in p for p in problems) == 1, f"{path}: {problems}"
    assert len(problems) == len(secrets)
