"""The world of each image: the other end of the set composition.

Kits are composed into a stage's sets; this is what comes out -- the flat, sorted
list of packages an image asks for. It is kept in the repository as
``variants/<stage>/world.<init>`` (``variants/minimal/world.systemd``,
``variants/flavor/kde/world.openrc``...), generated and never edited: a change to
any kit shows up as a diff of these files, and the test suite fails while one is
stale. The assembler writes the same list to the image's
``/var/lib/portage/world``, beside ``world_sets``.

Only explicit choices: the dependencies stay out, or depclean could never remove
one that became an orphan.
"""

from pathlib import Path

from shidashi.recipe import ResolvedRecipe, stage_layer
from shidashi.resolve import world_atoms

_HEADER = """\
# The packages the {image} image asks for -- GENERATED by `shidashi world`.
# Do not edit: change the kits (variants/kits/) or the stage's sets, then run
# `shidashi world` again. The image's /var/lib/portage/world holds this list.
"""


def world_file(recipe: ResolvedRecipe, variants_dir: Path) -> Path:
    """Where the repository keeps ``recipe``'s world: beside its last stage."""
    last = recipe.stages[-1] if recipe.stages else recipe.flavor
    return variants_dir / stage_layer(last) / f"world.{recipe.init}"


def render(recipe: ResolvedRecipe) -> str:
    """The repository file's text: a header, then one atom per line. I/O (kits)."""
    atoms = world_atoms(recipe)
    image = f"{recipe.flavor}/{recipe.init}"
    return _HEADER.format(image=image) + "".join(f"{a}\n" for a in atoms)


def read(path: Path) -> tuple[str, ...]:
    """The atoms of a world file, comments and blank lines skipped. I/O."""
    lines = path.read_text(encoding="utf-8").splitlines()
    return tuple(ln.strip() for ln in lines if ln.strip() and not ln.lstrip().startswith("#"))


def write_to_image(rootfs: Path, atoms: tuple[str, ...]) -> Path:
    """``/var/lib/portage/world`` of the image: the atoms, one per line. I/O."""
    path = rootfs / "var" / "lib" / "portage" / "world"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(f"{a}\n" for a in atoms), encoding="utf-8")
    return path


class StaleWorldError(Exception):
    """The repository's world file does not match what the kits compose."""


def current_atoms(recipe: ResolvedRecipe, variants_dir: Path) -> tuple[str, ...]:
    """The image's world, refused unless the repository's file says the same.

    An ISO whose package list differs from the committed one would make the file
    a lie -- the auditable list is only worth something if it is the truth.
    """
    path = world_file(recipe, variants_dir)
    atoms = world_atoms(recipe)
    if not path.is_file() or read(path) != atoms:
        raise StaleWorldError(
            f"{path} is out of date with the kits: run `shidashi world` and commit it"
        )
    return atoms
