#!/usr/bin/env bash
# Generate the laboratory's config tree from variants/.
#
# WHY THIS EXISTS
# ---------------
# `labrun` does not read variants/. It reads a copy under /xchg, and that copy
# was maintained by hand -- so it drifted. On 2026-09-11 the three lab steps ran
# against a config five days stale: sets/ still held the pre-split `graphics` and
# `bentoo-apps`, RUSTFLAGS still carried `-fuse-ld=mold` that make.conf had
# dropped on purpose, FEATURES still had ccache ON (which D10 says breaks the GCC
# build), and PORTAGE_LOGDIR was absent. The lab was testing a configuration that
# existed nowhere in the repository.
#
# This is the same failure as the duplicated _install_sets fixed in e7e47af: one
# rule, two implementations, kept in step by hand. Generating the copy removes
# the hand.
#
# It writes to *.new/ by default. Compare, then re-run with --apply.
set -euo pipefail

ARCH=v3
INIT=systemd
FLAVOR=kde
XCHG=/var/tmp/bentoo-lab/xchg
APPLY=0

usage() {
    cat >&2 <<USAGE
usage: ${0##*/} [--arch NAME] [--init NAME] [--flavor NAME] [--xchg DIR] [--apply]

Writes <xchg>/frag.new, <xchg>/cfg.new and <xchg>/<flavor>-layer.new.
With --apply, replaces the live directories, keeping a timestamped backup.
USAGE
    exit 2
}

while [ $# -gt 0 ]; do
    case "$1" in
        --arch)   ARCH=${2:?}; shift 2 ;;
        --init)   INIT=${2:?}; shift 2 ;;
        --flavor) FLAVOR=${2:?}; shift 2 ;;
        --xchg)   XCHG=${2:?}; shift 2 ;;
        --apply)  APPLY=1; shift ;;
        -h|--help) usage ;;
        *) echo "unknown argument: $1" >&2; usage ;;
    esac
done

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
V=$REPO/variants
BASE=$V/base/portage
ARCH_D=$V/arch/$ARCH/portage
INIT_D=$V/init/$INIT/portage
FLAVOR_D=$V/flavor/$FLAVOR

for d in "$BASE" "$ARCH_D" "$INIT_D" "$FLAVOR_D"; do
    [ -d "$d" ] || { echo "missing layer: $d" >&2; exit 1; }
done
[ -d "$XCHG" ] || { echo "missing xchg: $XCHG" >&2; exit 1; }

FRAG_NEW=$XCHG/frag.new
CFG_NEW=$XCHG/cfg.new
LAYER_NEW=$XCHG/$FLAVOR-layer.new
rm -rf "$FRAG_NEW" "$CFG_NEW" "$LAYER_NEW"
mkdir -p "$FRAG_NEW" "$CFG_NEW" "$LAYER_NEW"

banner() {
    printf '# GENERATED by scripts/%s from %s — do not edit.\n#\n' \
        "${0##*/}" "${1#"$REPO"/}"
}

# --- make.conf fragments ------------------------------------------------------
# step8 concatenates $FRAG/[0-9][0-9]-* in sort order. base and arch share NO
# keys (checked), so the split is presentation, not precedence.
{ banner "$ARCH_D/make.conf"; cat "$ARCH_D/make.conf"; } > "$FRAG_NEW/00-seed"
{
    banner "$BASE/make.conf + $INIT_D/make.conf"
    cat "$BASE/make.conf"
    printf '\n# --- init/%s ---\n' "$INIT"
    cat "$INIT_D/make.conf"
} > "$FRAG_NEW/50-use"

# --- package.* / env / repos.conf / bashrc ------------------------------------
for d in package.use package.mask package.accept_keywords package.env env repos.conf; do
    [ -d "$BASE/$d" ] || continue
    cp -a "$BASE/$d" "$CFG_NEW/$d"
done
[ -f "$BASE/bashrc" ] && cp -a "$BASE/bashrc" "$CFG_NEW/bashrc"

# The init layer contributes package.use entries. apply_portage merges layer
# directories as a union; /etc/portage/package.use is read the same way, so a
# distinct filename is all that is required.
if [ -d "$INIT_D/package.use" ]; then
    mkdir -p "$CFG_NEW/package.use"
    for f in "$INIT_D/package.use"/*; do
        [ -f "$f" ] || continue
        cp -a "$f" "$CFG_NEW/package.use/50-$INIT-${f##*/}"
    done
fi

# --- sets ---------------------------------------------------------------------
# Every base set, leaves and aggregators alike: Portage expands a nested @ref, so
# an aggregator without its leaves resolves to a missing target inside the
# container, far from the cause.
cp -a "$V/base/sets" "$CFG_NEW/sets"

# --- flavor layer -------------------------------------------------------------
[ -d "$FLAVOR_D/portage/package.use" ] && cp -a "$FLAVOR_D/portage/package.use" "$LAYER_NEW/package.use"
[ -f "$FLAVOR_D/portage/make.conf" ] && cp -a "$FLAVOR_D/portage/make.conf" "$LAYER_NEW/make.conf"
[ -d "$FLAVOR_D/sets" ] && cp -a "$FLAVOR_D/sets" "$LAYER_NEW/sets"

count() { find "$1" -type f 2>/dev/null | wc -l; }
echo "generated from ${REPO##*/} (arch=$ARCH init=$INIT flavor=$FLAVOR)"
printf '  %-22s %s files\n' "frag.new" "$(count "$FRAG_NEW")" \
                            "cfg.new" "$(count "$CFG_NEW")" \
                            "cfg.new/sets" "$(count "$CFG_NEW/sets")" \
                            "$FLAVOR-layer.new" "$(count "$LAYER_NEW")"

if [ "$APPLY" -eq 1 ]; then
    stamp=$(date +%Y%m%d-%H%M%S)
    for pair in "frag:$FRAG_NEW" "cfg:$CFG_NEW" "$FLAVOR-layer:$LAYER_NEW"; do
        live=$XCHG/${pair%%:*}
        new=${pair#*:}
        [ -e "$live" ] && mv "$live" "$live.bak-$stamp"
        mv "$new" "$live"
    done
    echo "applied; previous trees kept as *.bak-$stamp"
else
    echo "not applied — compare, then re-run with --apply"
fi
