#!/usr/bin/env bash
# Generate the laboratory's config tree from variants/.
#
# WHY THIS EXISTS
# ---------------
# `labrun` does not read variants/. It reads a copy under /xchg, and that copy
# was maintained by hand -- so it drifted. On 2026-09-11 the three lab steps ran
# against a config five days stale: sets/ still held the pre-split `graphics` and
# `bentoo-apps`, RUSTFLAGS still carried `-fuse-ld=mold` that make.conf had
# dropped on purpose, FEATURES still had ccache ON (which D10 says breaks the GCC
# build), and PORTAGE_LOGDIR was absent. The lab was testing a configuration that
# existed nowhere in the repository.
#
# This is the same failure as the duplicated _install_sets fixed in e7e47af: one
# rule, two implementations, kept in step by hand. Generating the copy removes
# the hand.
#
# It writes to *.new/ by default. Compare, then re-run with --apply.
set -euo pipefail

ARCH=v3
INIT=systemd
FLAVOR=kde
XCHG=/var/tmp/bentoo-lab/xchg
APPLY=0

usage() {
    cat >&2 <<USAGE
usage: ${0##*/} [--arch NAME] [--init NAME] [--flavor NAME] [--xchg DIR] [--apply]

Writes <xchg>/frag.new, <xchg>/cfg.new and <xchg>/<flavor>-layer.new.
With --apply, replaces the live directories, keeping a timestamped backup.
USAGE
    exit 2
}

while [ $# -gt 0 ]; do
    case "$1" in
        --arch)   ARCH=${2:?}; shift 2 ;;
        --init)   INIT=${2:?}; shift 2 ;;
        --flavor) FLAVOR=${2:?}; shift 2 ;;
        --xchg)   XCHG=${2:?}; shift 2 ;;
        --apply)  APPLY=1; shift ;;
        -h|--help) usage ;;
        *) echo "unknown argument: $1" >&2; usage ;;
    esac
done

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
V=$REPO/variants
BASE=$V/base/portage
ARCH_D=$V/arch/$ARCH/portage
INIT_D=$V/init/$INIT/portage
FLAVOR_D=$V/flavor/$FLAVOR   # a flavor stage; minimal/ and desktop/ are chain stages

for d in "$BASE" "$ARCH_D" "$INIT_D" "$FLAVOR_D"; do
    [ -d "$d" ] || { echo "missing layer: $d" >&2; exit 1; }
done
[ -d "$XCHG" ] || { echo "missing xchg: $XCHG" >&2; exit 1; }

FRAG_NEW=$XCHG/frag.new
CFG_NEW=$XCHG/cfg.new
LAYER_NEW=$XCHG/$FLAVOR-layer.new
rm -rf "$FRAG_NEW" "$CFG_NEW" "$LAYER_NEW"
mkdir -p "$FRAG_NEW" "$CFG_NEW" "$LAYER_NEW"

banner() {
    printf '# GENERATED by scripts/%s from %s — do not edit.\n#\n' \
        "${0##*/}" "${1#"$REPO"/}"
}

# --- make.conf fragments ------------------------------------------------------
# step8 concatenates $FRAG/[0-9][0-9]-* in sort order. base and arch share NO
# keys (checked), so the split is presentation, not precedence.
{ banner "$ARCH_D/make.conf"; cat "$ARCH_D/make.conf"; } > "$FRAG_NEW/00-seed"
{
    banner "$BASE/make.conf + $INIT_D/make.conf"
    cat "$BASE/make.conf"
    printf '\n# --- init/%s ---\n' "$INIT"
    cat "$INIT_D/make.conf"
} > "$FRAG_NEW/50-use"

# --- package.* / env / repos.conf / bashrc ------------------------------------
for d in package.use package.mask package.accept_keywords package.env env repos.conf; do
    [ -d "$BASE/$d" ] || continue
    cp -a "$BASE/$d" "$CFG_NEW/$d"
done
[ -f "$BASE/bashrc" ] && cp -a "$BASE/bashrc" "$CFG_NEW/bashrc"

# The init layer contributes package.use entries. apply_portage merges layer
# directories as a union; /etc/portage/package.use is read the same way, so a
# distinct filename is all that is required -- and since 7b7b0d8 the repo
# numbers files by layer itself (base 10-39, init 50-, flavor 60-), so the
# basename is copied as is. Prefixing again produced 50-systemd-50-systemd.
if [ -d "$INIT_D/package.use" ]; then
    mkdir -p "$CFG_NEW/package.use"
    for f in "$INIT_D/package.use"/*; do
        [ -f "$f" ] || continue
        [ -e "$CFG_NEW/package.use/${f##*/}" ] && { echo "package.use name clash: ${f##*/}" >&2; exit 1; }
        cp -a "$f" "$CFG_NEW/package.use/${f##*/}"
    done
fi

# --- sets ---------------------------------------------------------------------
# Written by shidashi.resolve.install_sets itself, not copied by hand: since D25
# every set lives in variants/kits/<category>/, and install_sets is what turns a
# recipe's declared sets -- with their nested @refs and the flavor's exclude --
# into /etc/portage/sets. Calling it here keeps one rule with one implementation.
# cfg/ gets minimal's sets (what the trunk and step13 install); the flavor layer
# gets its own recipe's, which step12 lays over them.
sets_for() {  # sets_for <flavor> <dest-dir>
    local tmp; tmp=$(mktemp -d)
    PYTHONPATH=$REPO SHIDASHI_VARIANTS_DIR=$V "$REPO/.venv/bin/python" - "$ARCH" "$INIT" "$1" "$tmp" <<'PYEOF'
import sys
from pathlib import Path
from shidashi import config
from shidashi.resolve import install_sets
arch, init, flavor, root = sys.argv[1:5]
r = config.load_recipe(arch, flavor, init)
install_sets(Path(root), r)
PYEOF
    mkdir -p "$2"; cp -a "$tmp/etc/portage/sets/." "$2/"; rm -rf "$tmp"
}
sets_for minimal "$CFG_NEW/sets"

# --- flavor layer -------------------------------------------------------------
[ -d "$FLAVOR_D/portage/package.use" ] && cp -a "$FLAVOR_D/portage/package.use" "$LAYER_NEW/package.use"
[ -f "$FLAVOR_D/portage/make.conf" ] && cp -a "$FLAVOR_D/portage/make.conf" "$LAYER_NEW/make.conf"
sets_for "$FLAVOR" "$LAYER_NEW/sets"

# --- emerge targets -----------------------------------------------------------
# The lab's step scripts used to spell the set names out: `@graphics @bentoo-apps`.
# After the split those two no longer exist, so step12 failed with "There are no
# sets to satisfy 'graphics'" -- the data had been synced, the target names had
# not. Deriving them from phase_target keeps one source of truth: the same
# function the Factory uses.
TARGETS_NEW=$XCHG/targets.sh.new
if PYTHONPATH=$REPO "$REPO/.venv/bin/python" - "$ARCH" "$INIT" "$FLAVOR" \
        > "$TARGETS_NEW" <<'PYEOF'
import os, sys
arch, init, flavor = sys.argv[1:4]
os.environ.setdefault("SHIDASHI_VARIANTS_DIR", "variants")
from shidashi import config
from shidashi.phases import phase_target

print("# GENERATED by scripts/sync-lab-cfg.sh — do not edit.")
print("# Emerge targets per flavor, derived from phase_target().")
for fl in ("minimal", flavor):
    r = config.load_recipe(arch, fl, init)
    seen, out = set(), []
    for phase in r.phases:
        for target in phase_target(phase, r):
            if target != "@world" and target not in seen:
                seen.add(target); out.append(target)
    var = fl.upper().replace("-", "_")
    print(f'TARGETS_{var}="{" ".join(out)}"')
PYEOF
then
    :
else
    echo "    !!! could not derive targets (is .venv present?)" >&2
    rm -f "$TARGETS_NEW"
fi

# --- the flavor's curated cycle break ----------------------------------------
# Same cycle, different valid cut per flavor: `minimal` breaks at
# ffmpeg[-sdl], but kde-apps/kdenlive needs ffmpeg[sdl], so kde cuts at
# pipewire[-ffmpeg] instead. Derived from the recipe so the lab cannot hold a
# stale choice.
for BREAK_FL in minimal "$FLAVOR"; do
BREAK_NEW=$XCHG/break-pass-$BREAK_FL.new
if PYTHONPATH=$REPO "$REPO/.venv/bin/python" - "$ARCH" "$INIT" "$BREAK_FL" \
        > "$BREAK_NEW" <<'PYEOF'
import os, sys
arch, init, flavor = sys.argv[1:4]
os.environ.setdefault("SHIDASHI_VARIANTS_DIR", "variants")
from shidashi import config
from shidashi.phases import use_break_lines

r = config.load_recipe(arch, flavor, init)
print(f"# TRANSIENT — the use_break of every stage in the {flavor} chain (D24).")
print("# The settle-pass undoes this; it is not the final USE.")
for phase in r.phases:
    for line in use_break_lines(phase):
        print(line)
PYEOF
then
    :
else
    echo "    !!! could not derive the break-pass for $BREAK_FL" >&2
    rm -f "$BREAK_NEW"
fi
done

count() { find "$1" -type f 2>/dev/null | wc -l; }
echo "generated from ${REPO##*/} (arch=$ARCH init=$INIT flavor=$FLAVOR)"
printf '  %-22s %s files\n' "frag.new" "$(count "$FRAG_NEW")" \
                            "cfg.new" "$(count "$CFG_NEW")" \
                            "cfg.new/sets" "$(count "$CFG_NEW/sets")" \
                            "$FLAVOR-layer.new" "$(count "$LAYER_NEW")"

if [ "$APPLY" -eq 1 ]; then
    stamp=$(date +%Y%m%d-%H%M%S)
    for bf in minimal "$FLAVOR"; do
        [ -f "$XCHG/break-pass-$bf.new" ] || continue
        [ -e "$XCHG/break-pass-$bf" ] && mv "$XCHG/break-pass-$bf" "$XCHG/break-pass-$bf.bak-$stamp"
        mv "$XCHG/break-pass-$bf.new" "$XCHG/break-pass-$bf"
    done
    [ -f "$TARGETS_NEW" ] && { [ -e "$XCHG/targets.sh" ] && mv "$XCHG/targets.sh" "$XCHG/targets.sh.bak-$stamp"; mv "$TARGETS_NEW" "$XCHG/targets.sh"; }
    for pair in "frag:$FRAG_NEW" "cfg:$CFG_NEW" "$FLAVOR-layer:$LAYER_NEW"; do
        live=$XCHG/${pair%%:*}
        new=${pair#*:}
        [ -e "$live" ] && mv "$live" "$live.bak-$stamp"
        mv "$new" "$live"
    done
    echo "applied; previous trees kept as *.bak-$stamp"
    cat <<'NEXT'

    NEXT: re-run the config steps, in order.

        labrun step8-full-use        <- the ONLY step that copies cfg/ into the
                                        container's /etc/portage (and it wipes
                                        99-break-pass, so 9a must follow)
        labrun step9b-config-check   <- the gate: ALL CHECKS PASSED
        labrun step9a-break-check    <- GRAPH CLOSES
        labrun step10-phase-resolve  <- every phase rc=0
        labrun step12-kde-resolve    <- only to re-measure the kde flavor; it
                                        restores /etc/portage on exit

    step12 applies just the flavor layer on top of whatever /etc/portage already
    holds. Running it alone after a sync resolves the PREVIOUS configuration and
    reports an error that was fixed already -- which is exactly what happened on
    2026-09-12: the uriparser fix sat in cfg/ while the rootfs still held the
    config from three days earlier.
NEXT
else
    echo "not applied — compare, then re-run with --apply"
fi
